-- MDF_FT_DEMO_META.META.CONTEXTS definition

create database MDF_FT_DEMO_META;
create schema MDF_FT_DEMO_META.META;

create or replace TABLE MDF_FT_DEMO_META.META.CONTEXTS (
	CONTEXT_ID NUMBER(38,0) NOT NULL,
	CONTEXT_GROUP_ID NUMBER(38,0),
	CONTEXT_KEY VARCHAR(100),
	CONTEXT_VALUE VARCHAR(2000),
	IS_ACTIVE BOOLEAN,
	constraint CONTEXTS_PK primary key (CONTEXT_ID)
);


-- MDF_FT_DEMO_META.META.CONTEXT_GROUP definition

create or replace TABLE MDF_FT_DEMO_META.META.CONTEXT_GROUP (
	CONTEXT_GROUP_ID NUMBER(12,0) NOT NULL,
	CONTEXT_GROUP_TYPE VARCHAR(50),
	CONTEXT_GROUP_DESC VARCHAR(50),
	IS_ACTIVE BOOLEAN,
	constraint CONTEXT_GROUP_PK primary key (CONTEXT_GROUP_ID)
);


-- MDF_FT_DEMO_META.META.LOB_MASTER definition

create or replace TABLE MDF_FT_DEMO_META.META.LOB_MASTER (
	LOB_CODE NUMBER(38,0) NOT NULL,
	LOB_NAME VARCHAR(100),
	IS_ACTIVE BOOLEAN,
	constraint LOB_MASTER_PK primary key (LOB_CODE)
);


-- MDF_FT_DEMO_META.META.MODULE_MASTER definition

create or replace TABLE MDF_FT_DEMO_META.META.MODULE_MASTER (
	MODULE_ID NUMBER(12,0) NOT NULL autoincrement start 201 increment 1,
	MODULE_NAME VARCHAR(100),
	CONTEXT_GROUP_ID NUMBER(12,0),
	DATAHUB_LOAD_TYPE VARCHAR(20),
	LOAD_SUCCESS_CONDITION VARCHAR(10),
	SCHEDULE_FREQUENCY VARCHAR(20),
	LAST_EXECUTION_TIME TIMESTAMP_NTZ(3),
	NEXT_EXECUTION_TIME TIMESTAMP_NTZ(3),
	IS_ACTIVE BOOLEAN,
	LOB_NAME VARCHAR(100),
	DEPENDENCY VARCHAR(200),
	constraint MODULE_MASTER_PK primary key (MODULE_ID)
);


-- MDF_FT_DEMO_META.META.OBJECT_MASTER definition

create or replace TABLE MDF_FT_DEMO_META.META.OBJECT_MASTER (
	OBJECT_ID NUMBER(12,0) NOT NULL autoincrement,
	OBJECT_NAME VARCHAR(100),
	OBJECT_TYPE VARCHAR(10),
	OBJECT_LOCATION VARCHAR(100),
	TARGET_NAME VARCHAR(100),
	OBJECT_UNIQUE_KEY VARCHAR(100),
	OBJECT_UPDATE_KEY VARCHAR(200),
	OBJECT_LOAD_TYPE VARCHAR(100),
	TARGET_LOCATION VARCHAR(10),
	CREATE_DATE TIMESTAMP_NTZ(3),
	CREATED_BY_ID VARCHAR(10),
	constraint OBJECT_MASTER_PK primary key (OBJECT_ID)
);


-- MDF_FT_DEMO_META.META.OBJECT_SCHEMA definition

create or replace TABLE MDF_FT_DEMO_META.META.OBJECT_SCHEMA (
	SCHEMA_ID NUMBER(38,0) NOT NULL autoincrement start 600 increment 1,
	OBJECT_ID NUMBER(12,0),
	COLUMN_NAME VARCHAR(100),
	COLUMN_ORDINAL NUMBER(12,0),
	COLUMN_DATATYPE VARCHAR(10),
	COLUMN_LENGTHE NUMBER(20,0),
	COLUMN_DESC VARCHAR(100),
	IS_COLUMN_REQUIRED NUMBER(1,0),
	IS_A_BUSINESS_KEY NUMBER(1,0),
	IS_MASK_REQUIRED NUMBER(1,0),
	IS_COLUMN_ENABLED NUMBER(1,0),
	constraint OBJECT_SCHEMA primary key (SCHEMA_ID)
);


-- MDF_FT_DEMO_META.META.PROCESS_MASTER definition

create or replace TABLE MDF_FT_DEMO_META.META.PROCESS_MASTER (
	PROCESS_ID NUMBER(12,0) NOT NULL autoincrement,
	PROCESS_NAME VARCHAR(10),
	constraint LOB_MASTER_PK primary key (PROCESS_ID)
);


-- MDF_FT_DEMO_META.META.RULES_MASTER definition

create or replace TABLE MDF_FT_DEMO_META.META.RULES_MASTER (
	RULE_ID NUMBER(12,0) NOT NULL autoincrement,
	RULE_NAME VARCHAR(100),
	RULE_TYPE VARCHAR(200),
	RULE_PURPOSE VARCHAR(200),
	RULE_DESC VARCHAR(4000),
	constraint RULE_ID_PK primary key (RULE_ID)
);


-- MDF_FT_DEMO_META.META.SUB_PROCESS_MASTER definition

create or replace TABLE MDF_FT_DEMO_META.META.SUB_PROCESS_MASTER (
	SUB_PROCESS_ID NUMBER(12,0) NOT NULL autoincrement,
	SUB_PROCESS_NAME VARCHAR(100),
	constraint LOB_MASTER_PK primary key (SUB_PROCESS_ID)
);


-- MDF_FT_DEMO_META.META.TFLOWMETERCATCHER definition

create or replace TABLE MDF_FT_DEMO_META.META.TFLOWMETERCATCHER (
	MOMENT TIMESTAMP_NTZ(3),
	PID VARCHAR(20),
	FATHER_PID VARCHAR(20),
	ROOT_PID VARCHAR(20),
	SYSTEM_PID NUMBER(38,0),
	PROJECT VARCHAR(50),
	JOB VARCHAR(255),
	JOB_REPOSITORY_ID VARCHAR(255),
	JOB_VERSION VARCHAR(255),
	CONTEXT VARCHAR(50),
	ORIGIN VARCHAR(255),
	LABEL VARCHAR(255),
	COUNT NUMBER(38,0),
	REFERENCE NUMBER(38,0),
	THRESHOLDS VARCHAR(255)
);


-- MDF_FT_DEMO_META.META.TLOGCATCHER definition

create or replace TABLE MDF_FT_DEMO_META.META.TLOGCATCHER (
	MOMENT TIMESTAMP_NTZ(3),
	PID VARCHAR(20),
	ROOT_PID VARCHAR(20),
	FATHER_PID VARCHAR(20),
	PROJECT VARCHAR(50),
	JOB VARCHAR(255),
	CONTEXT VARCHAR(50),
	PRIORITY NUMBER(38,0),
	TYPE VARCHAR(255),
	ORIGIN VARCHAR(255),
	MESSAGE VARCHAR(255),
	CODE NUMBER(38,0)
);


-- MDF_FT_DEMO_META.META.TSTATSCATCHER definition

create or replace TABLE MDF_FT_DEMO_META.META.TSTATSCATCHER (
	MOMENT TIMESTAMP_NTZ(3),
	PID VARCHAR(20),
	FATHER_PID VARCHAR(20),
	ROOT_PID VARCHAR(20),
	SYSTEM_PID NUMBER(38,0),
	PROJECT VARCHAR(50),
	JOB VARCHAR(255),
	JOB_REPOSITORY_ID VARCHAR(255),
	JOB_VERSION VARCHAR(255),
	CONTEXT VARCHAR(50),
	ORIGIN VARCHAR(255),
	MESSAGE_TYPE VARCHAR(255),
	MESSAGE VARCHAR(255),
	DURATION NUMBER(38,0)
);


-- MDF_FT_DEMO_META.META.DATAFLOW_AUDIT definition

create or replace TABLE MDF_FT_DEMO_META.META.DATAFLOW_AUDIT (
	AUDIT_ID VARCHAR(50) NOT NULL,
	MODULE_AUDIT_ID VARCHAR(50) NOT NULL,
	PID VARCHAR(50),
	MODULE_ID NUMBER(12,0) NOT NULL,
	PROCESS_ID NUMBER(12,0),
	SUB_PROCESS_ID NUMBER(12,0),
	OBJECT_ID NUMBER(12,0) NOT NULL,
	OBJECT_NAME VARCHAR(100),
	TARGET_NAME VARCHAR(100),
	RUN_STATUS VARCHAR(10),
	STATUS_MESSAGE VARCHAR(2000),
	CREATED_DATE TIMESTAMP_NTZ(3),
	constraint DATAFLOW_AUDIT_FK foreign key (MODULE_ID) references MDF_FT_DEMO_META.META.MODULE_MASTER(MODULE_ID)
);


-- MDF_FT_DEMO_META.META.DATAFLOW_MONITOR definition

create or replace TABLE MDF_FT_DEMO_META.META.DATAFLOW_MONITOR (
	DATAFLOW_ID NUMBER(12,0) NOT NULL,
	MODULE_ID NUMBER(12,0) NOT NULL,
	PROCESS_ID NUMBER(12,0),
	SUB_PROCESS_ID NUMBER(12,0),
	STATUS VARCHAR(10),
	FAILED_AUDIT_ID VARCHAR(100),
	ACTIVE_FLAG BOOLEAN,
	MODULE_AUDIT_ID VARCHAR(50),
	constraint DATAFLOW_MONITOR_PK primary key (DATAFLOW_ID),
	constraint DATAFLOW_MONITOR_FK foreign key (MODULE_ID) references MDF_FT_DEMO_META.META.MODULE_MASTER(MODULE_ID),
	constraint DATAFLOW_MONITOR_FK_1 foreign key (PROCESS_ID) references MDF_FT_DEMO_META.META.PROCESS_MASTER(PROCESS_ID),
	constraint DATAFLOW_MONITOR_FK_2 foreign key (SUB_PROCESS_ID) references MDF_FT_DEMO_META.META.SUB_PROCESS_MASTER(SUB_PROCESS_ID)
);


-- MDF_FT_DEMO_META.META.MODULE_OBJECT_REL definition

create or replace TABLE MDF_FT_DEMO_META.META.MODULE_OBJECT_REL (
	MODULE_OBJECT_ID NUMBER(12,0) NOT NULL autoincrement,
	MODULE_ID NUMBER(12,0),
	OBJECT_ID NUMBER(12,0),
	IS_ACTIVE BOOLEAN,
	OBJECT_ORDINAL NUMBER(38,0),
	constraint MODULE_OBJECT_REL_PK primary key (MODULE_OBJECT_ID),
	constraint MODULE_OBJECT_REL_FK foreign key (MODULE_ID) references MDF_FT_DEMO_META.META.MODULE_MASTER(MODULE_ID)
);


-- MDF_FT_DEMO_META.META.NOTIFICATION definition

create or replace TABLE MDF_FT_DEMO_META.META.NOTIFICATION (
	NOTIFICATION_ID NUMBER(12,0) NOT NULL autoincrement,
	MODULE_ID NUMBER(12,0) NOT NULL,
	NOTIFICATION_TO VARCHAR(100),
	NOTIFICATION_FROM VARCHAR(100),
	constraint NOTIFICATION_PK primary key (NOTIFICATION_ID),
	constraint NOTIFICATION_FK foreign key (MODULE_ID) references MDF_FT_DEMO_META.META.MODULE_MASTER(MODULE_ID)
);


-- MDF_FT_DEMO_META.META.OBJECT_RULE_REL definition

create or replace TABLE MDF_FT_DEMO_META.META.OBJECT_RULE_REL (
	OBJECT_RULE_ID NUMBER(12,0) NOT NULL autoincrement,
	MODULE_ID NUMBER(12,0),
	OBJECT_ID NUMBER(12,0),
	RULE_ID NUMBER(12,0),
	RULE_COLUMNS VARCHAR(2000),
	RULE_ORDINAL NUMBER(12,0),
	PROCESS_NAME VARCHAR(16777216),
	IS_ACTIVE BOOLEAN,
	constraint OBJECT_RULE_ID_PK primary key (OBJECT_RULE_ID),
	constraint OBJECT_RULE_REL_FK foreign key (RULE_ID) references MDF_FT_DEMO_META.META.RULES_MASTER(RULE_ID),
	constraint OBJECT_RULE_REL_FK_1 foreign key (MODULE_ID) references MDF_FT_DEMO_META.META.MODULE_MASTER(MODULE_ID)
);